version: '3'
services: 
    mysql:
        image: mysql:5.6
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=pfa
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=desafio02
        volumes: 
            - ./mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
            - ./mysql/dbdata:/var/lib/mysql
        networks: 
            - datanet
    pfa-api:
        build: 
            context: node-api
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 50s node index.js
        environment: 
            - DB_HOST=mysql
            - DB_DATABASE=desafio02
            - DB_USER=pfa
            - DB_PASSWORD=123456
        depends_on: 
            - mysql
        networks: 
            - datanet
            - apinet
    nginx:
        build: 
            context: nginx
        entrypoint: "dockerize -wait http://pfa-api:3000 -timeout 60s ./docker-entrypoint.sh nginx -g 'daemon off;'"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 8000:80
        depends_on: 
            - pfa-api
        networks: 
            - apinet
networks: 
    datanet:
    apinet:
